<#import "common/base.ftlh" as base>

<@base.page>
  <div class="slide-one-item home-slider owl-carousel">

    <div class="site-blocks-cover inner-page-cover" style="background-image: url(/static/images/hero_bg_2.jpg);" data-aos="fade"
         data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">

          <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
            <h2 class="text-white font-weight-light mb-2 display-1">О нас</h2>
          </div>
        </div>
      </div>
    </div>

  </div>
  <!-- Мастера -->
  <div class="site-section bg-light">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7">
          <h2 class="site-section-heading font-weight-light text-black text-center">Our Barbers</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_1.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Елена Петрова</h2>
          <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est
            odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_2.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">София Ратару</h2>
          <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est
            odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_4.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Тимофей Загробный</h2>
          <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ab quas facilis obcaecati non ea, est
            odit repellat distinctio incidunt, quia aliquam eveniet quod deleniti impedit sapiente atque tenetur porro?</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Цитата -->
  <div class="site-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5">
          <img src="/static/images/person_1.jpg" alt="Image" class="img-md-fluid">
        </div>
        <div class="col-lg-6 bg-white p-md-5 align-self-center">
          <h2 class="display-1 text-black line-height-1 site-section-heading mb-4 pb-3">Новый образ!</h2>
          <p class="text-black lead"><em>&ldquo;ВСТАВИТЬ ТУТ ЦИТАТУ ПРО КРАСОТУ ОТ КОГО ТО &rdquo;</em></p>
          <p class="lead text-black">&mdash; <em>Кто то крутой!</em></p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section border-top">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h2 class="mb-4 text-black">Ждем Вас скорее на процедуры!</h2>
          <p class="mb-0"><a href="/appointment/" class="btn btn-primary py-3 px-5 text-white">Посетить салон</a></p>
        </div>
      </div>
    </div>
  </div>

</@base.page>