<#import "common/base.ftlh" as base>

<@base.page>
  <div class="slide-one-item home-slider owl-carousel">

    <div class="site-blocks-cover inner-page-cover" style="background-image: url(/static/images/hero_bg_2.jpg);" data-aos="fade"
         data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">

          <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
            <h2 class="text-white font-weight-light mb-2 display-1">О нас</h2>
          </div>
        </div>
      </div>
    </div>

  </div>
  <!-- Мастера -->
  <div class="site-section bg-light">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7">
          <h2 class="site-section-heading font-weight-light text-black text-center">Наши мастера</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_1.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Елена Петрова</h2>
          <p class="mb-4">профессиональный мастер с многолетним опытом в сфере красоты и ухода. Специализируется на стрижках,
            укладках, окрашивании, а также уходе за волосами и кожей. Благодаря индивидуальному подходу и вниманию к деталям,
            Елена всегда создает образы, которые подчеркивают естественную красоту каждого клиента. Она внимательно слушает
            пожелания и использует только высококачественные косметические средства, обеспечивая лучший результат. Если вы хотите
            почувствовать себя на высоте, запишитесь на прием к Елене!</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_2.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">София Ратару</h2>
          <p class="mb-4">опытный специалист с глубокими знаниями в области ухода за волосами и кожей. Ее подход к каждому клиенту
            индивидуален, она всегда учитывает особенности типа волос и потребности кожи, чтобы создать идеальный образ. София
            мастерски выполняет стрижки, окрашивания, укладки и делает акцент на здоровье волос. Используя только лучшие
            косметические средства и техники, она добивается невероятных результатов, даря клиентам уверенность и красоту. Если вы
            хотите стать обладателем стильной прически, запишитесь на прием к Софии!</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="/static/images/person_4.jpg" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Тимофей Загробный</h2>
          <p class="mb-4">высококлассный мастер с многолетним опытом в области стрижек и мужских укладок. Его внимательность к
            деталям и умение слушать клиента делают каждую стрижку уникальной. Тимофей использует только качественные инструменты
            и средства для ухода за волосами, обеспечивая идеальный результат. Независимо от того, хотите ли вы классическую или
            современную стрижку, он всегда предложит оптимальное решение для вашего образа. Запишитесь к Тимофею и ощутите
            разницу!</p>
          <p>
            <a href="#" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="#" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Цитата -->
  <div class="site-section bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-5">
          <img src="/static/images/coco.jpg" style="max-width: 650px; max-height: 570px" alt="Image" class="img-md-fluid">
        </div>
        <div class="col-lg-6 bg-white p-md-5 align-self-center">
          <h2 class="display-1 text-black line-height-1 site-section-heading mb-4 pb-3">Новый образ!</h2>
          <p class="text-black lead"><em>&ldquo;Красота начинается с уверенности в себе и умения принимать свою индивидуальность.&rdquo;</em></p>
          <p class="lead text-black">&mdash; <em>Коко Шанель</em></p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section border-top">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h2 class="mb-4 text-black">Ждем Вас скорее на процедуры!</h2>
          <p class="mb-0"><a href="/appointment/" class="btn btn-black py-3 px-5">Посетить салон</a></p>
        </div>
      </div>
    </div>
  </div>

</@base.page>