<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="mb-5">
          <h3 class="footer-heading mb-4">О BeautyPlace</h3>
          <p>BeautyPlace — место, где профессиональный уход и стиль сочетаются с качеством. Доверьте нам свою красоту!
          </p>
        </div>
      </div>
      <div class="col-lg-4 mb-5 mb-lg-0">
        <div class="row mb-5">
          <div class="col-md-12">
            <h3 class="footer-heading mb-4">Быстрое меню</h3>
          </div>
          <div class="col-md-6 col-lg-6">
            <ul class="list-unstyled">
              <li><a href="/">Главная</a></li>
              <li><a href="/">Мастера</a></li>
              <li><a href="/">Новости красоты</a></li>
              <li><a href="/">Команда</a></li>
            </ul>
          </div>
          <div class="col-md-6 col-lg-6">
            <ul class="list-unstyled">
              <li><a href="/about">О нас</a></li>
              <li><a href="/">Политика приватности</a></li>
              <li><a href="/">Контакты</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <div class="mb-5">
          <a href="facebook.com" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
          <a href="x.com" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
          <a href="instagram.com" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
        </div>
      </div>
    </div>
  </div>
</footer>